"""
Django settings for geospatialib project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VENV_BASE, 'Lib\\\\site-packages\\\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Lib\\\\site-packages\\\\osgeo\\\\data\\\\proj') + ';' + os.environ['PATH']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = os.path.join(BASE_DIR, 'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--!^$7x&a6b$0lbvp!z8tw*&@a%wtqe)*%_f@_sdf3%0a-zv$g9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1', '127.0.0.1:8000',
    '192.168.1.103', '192.168.1.103:8000', # python manage.py runserver 0.0.0.0:8000
    # '192.168.1.6',
    # 'geospatialib.com',
    # 'www.geospatialib.com',
]

SITE_ID = 1
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online'
        },
    }
}

SOCIALACCOUNT_ADAPTER = 'apps.main.adapters.CustomSocialAccountAdapter'

AUTHENTICATION_BACKENDS = (
    'apps.main.backends.CustomAuthenticationBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

AUTH_USER_MODEL = 'main.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # social auth
    'django.contrib.sites',
    'allauth',    
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',          

    # postgres
    'django.contrib.postgres',
    
    # gis
    'django.contrib.gis',

    # local apps
    'utils',
    'htmx.hx_main',
    'htmx.hx_library',
    'htmx.hx_map',
    'apps.main',
    'apps.library',
    'apps.map',

    # 3rd-party apps
    'widget_tweaks',
    'leaflet',
    'django_htmx',
    'debug_toolbar',
    'django_recaptcha',
    'corsheaders',
]

LEAFLET_CONFIG = {
    # 'SPATIAL_EXTENT': (5.0, 44.0, 7.5, 46),
    
    'DEFAULT_CENTER': (45, 0),
    'DEFAULT_ZOOM': 2,
    'MIN_ZOOM': 1,
    'MAX_ZOOM': 20,
    'DEFAULT_PRECISION': 6,
    
    'TILES': [],
    # 'OVERLAYS': [('Cadastral', 'http://server/a/{z}/{x}/{y}.png', {'attribution': '&copy; IGN'})],
    # 'ATTRIBUTION_PREFIX': 'Powered by django-leaflet',
    

    'SCALE': None,
    # 'MINIMAP': True,
    'RESET_VIEW': True,

    'NO_GLOBALS': False,
    'FORCE_IMAGE_PATH': True,

    'PLUGINS': {
        'geocoder': {
            'css': [
                'https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.css', 
            ],
            'js': [
                'https://unpkg.com/leaflet-control-geocoder/dist/Control.Geocoder.js'
            ],
            'auto_include': True,
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # social auth
    'allauth.account.middleware.AccountMiddleware',

    # 3rd party
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    # local
    'apps.main.middleware.RedirectCancelledSocialLogin',
    'htmx.hx_main.middleware.HTMXDomainRestriction',
]

ROOT_URLCONF = 'geospatialib.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.context_processors.forms',
                'apps.main.context_processors.social',
                'apps.library.context_processors.forms',
                'apps.map.context_processors.forms',
            ],
        },
    },
]

WSGI_APPLICATION = 'geospatialib.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "geospatialib-lite",
        "USER": "geospatialib",
        "PASSWORD": "geospatialib",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

# NOTE: 
# Create postgis extension in database
# pip install pipwin
# pip install psycopg2
# pipwin install gdal 
# https://github.com/ranjanport/GDAL/releases

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# for debug toolbar
INTERNAL_IPS = [
    '127.0.0.1'
]

# for captcha
RECAPTCHA_PUBLIC_KEY = '6LcNimkqAAAAAKstLLJ6qiuIpuHMiwusF7oh9ylF'
RECAPTCHA_PRIVATE_KEY = '6LcNimkqAAAAALA06RHsr8Gd3u4v55YWlXA5G_eN'

# for cors header
CORS_ALLOWED_ORIGINS = []