# Generated by Django 5.1.2 on 2024-10-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='join_data',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Join date'),
        ),
    ]
