# Generated by Django 5.1.2 on 2024-10-22 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_user_join_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='join_data',
            new_name='join_date',
        ),
    ]
