# Generated by Django 5.1.2 on 2024-10-22 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_user_loggedin_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loggedin_on',
            new_name='lastloggedin_on',
        ),
    ]
