# Generated by Django 5.1.2 on 2024-10-22 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_loggedin_on_user_lastloggedin_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Join date'),
        ),
    ]
