# Generated by Django 5.1.2 on 2024-10-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_user_joined_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastloggedin_on',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last log in'),
        ),
    ]
