# Generated by Django 5.1.2 on 2024-10-24 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
    ]
