# Generated by Django 5.1.2 on 2024-11-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8, verbose_name='Dashboard privacy'),
        ),
        migrations.AddField(
            model_name='user',
            name='map_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8, verbose_name='Default map privacy'),
        ),
    ]
