# Generated by Django 5.1.2 on 2024-11-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_user_dashboard_privacy_user_map_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dashboard_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8, verbose_name='Dashboard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='map_privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8, verbose_name='Map (default)'),
        ),
    ]
