# Generated by Django 5.1.2 on 2024-11-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_map_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplog',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Remark'),
        ),
    ]
