# Generated by Django 5.1.2 on 2024-11-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_maplog_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='updated_on',
        ),
    ]
