# Generated by Django 5.1.2 on 2024-12-02 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_map_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='owner_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Owner since'),
        ),
        migrations.AlterField(
            model_name='map',
            name='privacy',
            field=models.CharField(choices=[('default', "Owner's default map privacy"), ('public', 'Public'), ('private', 'Private')], default='default', max_length=8, verbose_name='Privacy'),
        ),
    ]
