# Generated by Django 5.1.2 on 2024-12-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_map_owner_since_alter_map_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplog',
            name='action',
            field=models.CharField(blank=True, choices=[('set', 'Set'), ('removed', 'Removed'), ('changed', 'Changed')], max_length=8, null=True, verbose_name='Action'),
        ),
    ]
