# Generated by Django 5.1.2 on 2024-12-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_maplog_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplog',
            name='action',
        ),
        migrations.AlterField(
            model_name='maplog',
            name='field',
            field=models.CharField(max_length=32, verbose_name='Field'),
        ),
    ]
