# Generated by Django 5.1.2 on 2024-12-02 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_maplog_action_alter_maplog_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplog',
            name='user',
        ),
        migrations.AddField(
            model_name='map',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_added', to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='map',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added on'),
        ),
        migrations.AddField(
            model_name='map',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='map',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AddField(
            model_name='maplog',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='mapreference',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_added', to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='mapreference',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added on'),
        ),
        migrations.AddField(
            model_name='mapreference',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AddField(
            model_name='mapreference',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on'),
        ),
        migrations.AddField(
            model_name='maprole',
            name='added_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_added', to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AddField(
            model_name='maprole',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
