# Generated by Django 5.1.2 on 2024-12-04 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_maplog_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maplog',
            old_name='field',
            new_name='field_exp',
        ),
    ]
