# Generated by Django 5.1.2 on 2024-12-04 10:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_rename_field_maplog_field_exp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MapRole',
            new_name='MapContributor',
        ),
    ]
