# Generated by Django 5.1.2 on 2024-12-04 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_rename_maprole_mapcontributor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapcontributor',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='map.map', verbose_name='Map'),
        ),
    ]
