# Generated by Django 5.1.2 on 2024-12-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_mapcontributor_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplog',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Added on'),
        ),
    ]
