# Generated by Django 5.1.2 on 2024-12-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_alter_maplog_added_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplog',
            name='action',
            field=models.CharField(blank=True, choices=[('set as', 'Set'), ('removed from', 'Removed'), ('changed to', 'Changed'), ('added to', 'Added'), ('created', 'Created')], max_length=16, null=True, verbose_name='Action'),
        ),
    ]
