# Generated by Django 5.1.2 on 2024-12-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_alter_maplog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maplog',
            name='action',
            field=models.CharField(blank=True, choices=[('set', 'Set'), ('removed', 'Removed'), ('changed', 'Changed'), ('added', 'Added'), ('created', 'Created')], max_length=8, null=True, verbose_name='Action'),
        ),
    ]
