# Generated by Django 5.1.2 on 2024-12-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_alter_maplog_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maplog',
            options={'ordering': ['-added_on']},
        ),
        migrations.AlterField(
            model_name='maplog',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Added on'),
        ),
    ]
