# Generated by Django 5.1.2 on 2024-12-12 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_rename_label_content_title'),
        ('map', '0018_alter_maplog_options_alter_maplog_added_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mapreference',
            unique_together={('map', 'url')},
        ),
    ]
