# Generated by Django 5.1.2 on 2024-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_alter_mapreference_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapreference',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='mapreference',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Order'),
        ),
    ]
