# Generated by Django 5.1.2 on 2024-12-17 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_alter_mapreference_options_mapreference_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapReference',
        ),
    ]
