# Generated by Django 5.1.2 on 2024-12-18 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0005_rename_label_content_title'),
        ('map', '0021_delete_mapreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Added on')),
                ('updated_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated on')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('added_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_added', to=settings.AUTH_USER_MODEL, verbose_name='Added by')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='map.map', verbose_name='Map')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library.url', verbose_name='URL')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('map', 'url')},
            },
        ),
    ]
