# Generated by Django 5.1.2 on 2024-12-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_mapreference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mapreference',
            options={'ordering': ['order', 'id']},
        ),
    ]
