# Generated by Django 5.1.2 on 2024-12-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_alter_mapreference_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maplog',
            name='remark',
        ),
    ]
