# Generated by Django 5.1.2 on 2024-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_remove_maplog_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplog',
            name='field_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field type'),
        ),
        migrations.AddField(
            model_name='maplog',
            name='value_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Value type'),
        ),
    ]
