# Generated by Django 5.1.2 on 2024-12-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_maplog_field_type_maplog_value_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapLog',
        ),
    ]
